# This workflow will build a Java project with Maven, and cache/restore any dependencies
#to improve the workflow execution time

name: Java CI with Maven

on:
  #for triggering actions manually
  workflow_dispatch:

  #for triggering when push on master branch
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    # mvn -B package command will go through compile, test and build
    - name: Build artifacts with Maven
      run: mvn -B package --file TourGuide/pom.xml

    #saves and uploads the JAR file created from each build
    - name: Upload JAR file
      uses: actions/upload-artifact@v3
      with:
        name: tourguide
        path: TourGuide/target/*.jar
